#Makefile - compiler for Lab 1
  
# compiler flags.  -g for debug, -O3 for optimization
CFLAGS=-g -O3

#tokenizerlab: echo.o tokenizer.o history.o
#		cc -o token echo.o tokenizer.o history.o

#echo.o:	echo.c history.h tokenizer.h

#tokenizer.o: tokenizer.h tokenizer.c

#history.o: history.h history.c

#echo:
#	gcc -o tokens echo.c tokenizer.c 
make:
	gcc -o tokens echo.c


clean:
	rm -f *.o tokens
